// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AirVinyContext.Entities;

[Table("Rating")]
[Index("RatedByPersonId", Name = "IX_Rating_RatedByPersonId")]
[Index("RecordStoreId", Name = "IX_Rating_RecordStoreId")]
public partial class Rating
{
    [Key]
    public int RatingId { get; set; }

    public int Value { get; set; }

    public int RatedByPersonId { get; set; }

    public int RecordStoreId { get; set; }

    [ForeignKey("RatedByPersonId")]
    [InverseProperty("Ratings")]
    public virtual Person RatedByPerson { get; set; } = null!;

    [ForeignKey("RecordStoreId")]
    [InverseProperty("Ratings")]
    public virtual RecordStore RecordStore { get; set; } = null!;
}