// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AirVinyContext.Entities;

[Index("PersonId", Name = "IX_VinylRecords_PersonId")]
[Index("PressingDetailId", Name = "IX_VinylRecords_PressingDetailId")]
public partial class VinylRecord
{
    [Key]
    public int VinylRecordId { get; set; }

    [StringLength(150)]
    public string Title { get; set; } = null!;

    [StringLength(150)]
    public string Artist { get; set; } = null!;

    [StringLength(50)]
    public string? CatalogNumber { get; set; }

    public int? Year { get; set; }

    public int PressingDetailId { get; set; }

    public int PersonId { get; set; }

    [ForeignKey("PersonId")]
    [InverseProperty("VinylRecords")]
    public virtual Person Person { get; set; } = null!;

    [ForeignKey("PressingDetailId")]
    [InverseProperty("VinylRecords")]
    public virtual PressingDetail PressingDetail { get; set; } = null!;
}