// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AirVinyContext.Entities;

public partial class MyAirVinylCtx : DbContext
{
    public MyAirVinylCtx(DbContextOptions<MyAirVinylCtx> options)
        : base(options)
    {
    }

    public virtual DbSet<Person> People { get; set; }

    public virtual DbSet<PressingDetail> PressingDetails { get; set; }

    public virtual DbSet<Rating> Ratings { get; set; }

    public virtual DbSet<RecordStore> RecordStores { get; set; }

    public virtual DbSet<VinylRecord> VinylRecords { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}