// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using AirVinyContext.Entities.lib;
using Microsoft.EntityFrameworkCore;

namespace AirVinyContext.Entities;

public partial class Person
{
    [Key]
    public int PersonId { get; set; }

    [StringLength(100)]
    public string? Email { get; set; }

    [StringLength(50)]
    public string FirstName { get; set; } = null!;

    [StringLength(50)]
    public string LastName { get; set; } = null!;

    public DateTimeOffset DateOfBirth { get; set; }

    public Gender Gender { get; set; }

    public int NumberOfRecordsOnWishList { get; set; }

    [Column(TypeName = "decimal(8, 2)")]
    public decimal AmountOfCashToSpend { get; set; }

    public IList<VinylRecord> VinylRecords { get; set; } = [];

    //public virtual IList<Rating> Ratings { get; set; } = [];

}