// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AirVinyContext.Entities;

public partial class PressingDetail
{
    [Key]
    public int Id { get; set; }

    public int Grams { get; set; }

    public int Inches { get; set; }

    [StringLength(200)]
    public string Description { get; set; } = null!;

    //public virtual IList<VinylRecord> VinylRecords { get; set; } = [];
}