// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AirVinyContext.Entities;

public partial class Rating
{
    [Key]
    public int RatingId { get; set; }

    public int Value { get; set; }

    public int PersonId { get; set; }

    public int RecordStoreId { get; set; }

    //public virtual Person Person { get; set; } = null!;

    //public virtual RecordStore RecordStore { get; set; } = null!;
}