// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using AirVinyContext.Entities.lib;
using Microsoft.EntityFrameworkCore;

namespace AirVinyContext.Entities;

public partial class RecordStore
{
    [Key]
    public int Id { get; set; }

    [StringLength(150)]
    public string Name { get; set; } = null!;

    public Address? StoreAddress { get; set; }

    public List<string> Tags { get; set; } = new List<string>();

    [StringLength(34)]
    public string Discriminator { get; set; } = null!;

    //public virtual IList<Rating> Ratings { get; } = [];
}