// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Delta.Infrastructure.DbEntities;

namespace Delta.Infrastructure.DataSources
{
    public partial class WeatherDbCtx
    {

        [DbFunction("NewComb", "dbo")]
        public static Guid? NewComb()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        public async Task<Guid?> NewCombAsync()
            => await Database.SqlQueryRaw<Guid?>("select Value = [dbo].[NewComb]()").SingleAsync();

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
