// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Delta.Infrastructure.DbEntities;
using Microsoft.EntityFrameworkCore;

namespace Delta.Infrastructure.DataSources;

public partial class WeatherDbCtx : DbContext
{
    public WeatherDbCtx(DbContextOptions<WeatherDbCtx> options)
        : base(options)
    {
    }

    public virtual DbSet<VwNewGuid> VwNewGuid { get; set; }

    public virtual DbSet<WeatherForecast> WeatherForecast { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<VwNewGuid>(entity =>
        {
            entity.ToView("vwNewGuid");
        });

        modelBuilder.Entity<WeatherForecast>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Id_WeatherForecast");

            entity.Property(e => e.Id).HasDefaultValueSql("([dbo].[NewComb]())");
        });

        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}