// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Delta.Infrastructure.DbEntities;

[Keyless]
public partial class VwNewGuid
{
    [Column("id")]
    public Guid? Id { get; set; }
}