// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Delta.Infrastructure.DbEntities;

public partial class WeatherForecast
{
    [Key]
    public Guid Id { get; set; }

    public DateTime Date { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal Temperature { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? Summary { get; set; }
}