// <auto-generated />
using System;
using AirVinyContext.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirVinyContext.Migrations
{
    [DbContext(typeof(MyAirVinylCtx))]
    [Migration("20250909190022_BuildDatabase")]
    partial class BuildDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirVinyContext.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<decimal>("AmountOfCashToSpend")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumberOfRecordsOnWishList")
                        .HasColumnType("int");

                    b.HasKey("PersonId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            AmountOfCashToSpend = 300m,
                            DateOfBirth = new DateTimeOffset(new DateTime(1981, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "kevin@kevindockx.com",
                            FirstName = "Kevin",
                            Gender = 1,
                            LastName = "Dockx",
                            NumberOfRecordsOnWishList = 10
                        },
                        new
                        {
                            PersonId = 2,
                            AmountOfCashToSpend = 2000m,
                            DateOfBirth = new DateTimeOffset(new DateTime(1986, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            Email = "sven@someemailprovider.com",
                            FirstName = "Sven",
                            Gender = 1,
                            LastName = "Vercauteren",
                            NumberOfRecordsOnWishList = 34
                        },
                        new
                        {
                            PersonId = 3,
                            AmountOfCashToSpend = 100m,
                            DateOfBirth = new DateTimeOffset(new DateTime(1977, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            Email = "nele@someemailprovider.com",
                            FirstName = "Nele",
                            Gender = 0,
                            LastName = "Verheyen",
                            NumberOfRecordsOnWishList = 120
                        },
                        new
                        {
                            PersonId = 4,
                            AmountOfCashToSpend = 2500m,
                            DateOfBirth = new DateTimeOffset(new DateTime(1983, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "nils@someemailprovider.com",
                            FirstName = "Nils",
                            Gender = 1,
                            LastName = "Missorten",
                            NumberOfRecordsOnWishList = 23
                        },
                        new
                        {
                            PersonId = 5,
                            AmountOfCashToSpend = 90m,
                            DateOfBirth = new DateTimeOffset(new DateTime(1981, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "tim@someemailprovider.com",
                            FirstName = "Tim",
                            Gender = 1,
                            LastName = "Van den Broeck",
                            NumberOfRecordsOnWishList = 19
                        },
                        new
                        {
                            PersonId = 6,
                            AmountOfCashToSpend = 200m,
                            DateOfBirth = new DateTimeOffset(new DateTime(1981, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            FirstName = "Kenneth",
                            Gender = 1,
                            LastName = "Mills",
                            NumberOfRecordsOnWishList = 98
                        });
                });

            modelBuilder.Entity("AirVinyContext.Entities.VinylRecord", b =>
                {
                    b.Property<int>("VinylRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VinylRecordId"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CatalogNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("VinylRecordId");

                    b.HasIndex("PersonId");

                    b.ToTable("VinylRecords");

                    b.HasData(
                        new
                        {
                            VinylRecordId = 1,
                            Artist = "Nirvana",
                            CatalogNumber = "ABC/111",
                            PersonId = 1,
                            Title = "Nevermind",
                            Year = 1991
                        },
                        new
                        {
                            VinylRecordId = 2,
                            Artist = "Arctic Monkeys",
                            CatalogNumber = "EUI/111",
                            PersonId = 1,
                            Title = "AM",
                            Year = 2013
                        },
                        new
                        {
                            VinylRecordId = 3,
                            Artist = "Beatles",
                            CatalogNumber = "DEI/113",
                            PersonId = 1,
                            Title = "The White Album",
                            Year = 1968
                        },
                        new
                        {
                            VinylRecordId = 4,
                            Artist = "Beatles",
                            CatalogNumber = "DPI/123",
                            PersonId = 1,
                            Title = "Sergeant Pepper's Lonely Hearts Club Band",
                            Year = 1967
                        },
                        new
                        {
                            VinylRecordId = 5,
                            Artist = "Nirvana",
                            CatalogNumber = "DPI/123",
                            PersonId = 1,
                            Title = "Bleach",
                            Year = 1989
                        },
                        new
                        {
                            VinylRecordId = 6,
                            Artist = "Leonard Cohen",
                            CatalogNumber = "PPP/783",
                            PersonId = 1,
                            Title = "Suzanne",
                            Year = 1967
                        },
                        new
                        {
                            VinylRecordId = 7,
                            Artist = "Marvin Gaye",
                            CatalogNumber = "MVG/445",
                            PersonId = 1,
                            Title = "What's Going On"
                        },
                        new
                        {
                            VinylRecordId = 8,
                            Artist = "Nirvana",
                            CatalogNumber = "ABC/111",
                            PersonId = 2,
                            Title = "Nevermind",
                            Year = 1991
                        },
                        new
                        {
                            VinylRecordId = 9,
                            Artist = "Cher",
                            CatalogNumber = "CHE/190",
                            PersonId = 2,
                            Title = "Closer to the Truth",
                            Year = 2013
                        },
                        new
                        {
                            VinylRecordId = 10,
                            Artist = "The Dandy Warhols",
                            CatalogNumber = "TDW/516",
                            PersonId = 3,
                            Title = "Thirteen Tales From Urban Bohemia"
                        },
                        new
                        {
                            VinylRecordId = 11,
                            Artist = "Justin Bieber",
                            CatalogNumber = "OOP/098",
                            PersonId = 4,
                            Title = "Baby"
                        },
                        new
                        {
                            VinylRecordId = 12,
                            Artist = "The Prodigy",
                            CatalogNumber = "NBE/864",
                            PersonId = 4,
                            Title = "Music for the Jilted Generation"
                        },
                        new
                        {
                            VinylRecordId = 13,
                            Artist = "Anne Clarke",
                            CatalogNumber = "TII/339",
                            PersonId = 5,
                            Title = "Our Darkness"
                        },
                        new
                        {
                            VinylRecordId = 14,
                            Artist = "Dead Kennedys",
                            CatalogNumber = "DKE/864",
                            PersonId = 5,
                            Title = "Give Me Convenience or Give Me Death"
                        },
                        new
                        {
                            VinylRecordId = 15,
                            Artist = "Sisters of Mercy",
                            CatalogNumber = "IIE/824",
                            PersonId = 5,
                            Title = "Temple of Love"
                        },
                        new
                        {
                            VinylRecordId = 16,
                            Artist = "Abba",
                            CatalogNumber = "TDW/516",
                            PersonId = 6,
                            Title = "Gimme Gimme Gimme"
                        });
                });

            modelBuilder.Entity("AirVinyContext.Entities.VinylRecord", b =>
                {
                    b.HasOne("AirVinyContext.Entities.Person", null)
                        .WithMany("VinylRecords")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirVinyContext.Entities.Person", b =>
                {
                    b.Navigation("VinylRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
